name: Test package

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9","3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install
      - name: Check Format
        run: poetry run invoke format --check
      - name: Linter check
        run: poetry run invoke lint-flake8 # only use flake for now due to a bug in pytest
      - name: Run tests
        run: poetry run invoke test
